# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
resources:
  pipelines: # The pipelines specify which pipeline this pipeline will pull artifacts from. In this case we will deploy from the test build's artifacts
    - pipeline: buildPipeline  # pipeline name (DO NOT CHANGE THIS VALUE) 
      source: deploy-validation-ALMAcceleratorSampleSolution # This is the name of the build pipeline that contains the artifacts to be deployed by this pipeline. NOTE: There must be a successful build for this pipeline available in order to run this pipeline
pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: 'AA4AM'
    pipeline: '6'
    buildVersionToDownload: 'latest'
    downloadType: 'specific'
    downloadPath: '$(Pipeline.Workspace)\buildPipeline'

- powershell: 
    Get-ChildItem -Path '$(Build.ArtifactStagingDirectory)' -recurse

- task: GitHubRelease@1
  displayName: 'GitHub release (create)'
  inputs:
    gitHubConnection: mikefactorial
    tagSource: userSpecifiedTag
    tag: 1.8
    title: 'Testing Release'
    releaseNotesSource: inline
    releaseNotesInline: 'Here''s some release notes'
    changeLogType: issueBased
    assets: |
      $(Pipeline.Workspace)/buildPipeline/drop/*.zip